services:
  api:
    build:
      context: .
      dockerfile: MessengerApp.WebAPI/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - connectionstrings__defaultconnection=host=db;database=postgres;username=postgres;password=Bugg3roff
    depends_on:
      - db
    # ... other options

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Bugg3roff
    ports:
      - "5432:5432"
